6pm-2 Finished API Add a Course to Personal Course Database
ucsb-cs156-s22/s22-6pm-courses pull request #26
Opened 2022-05-26 23:54 UTC by Sean-syf

2022-05-27 18:10 UTC, austinmacmath submitted a review, later dismissed
lgtm

2022-05-30 17:10 UTC, pconrad requested changes
LGTM except for one line of commented out code that we should probably remove.

I'll test on Heroku in the meantime.

2022-05-30 17:10 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
> +        //personalcourse.getPersonalSchedule().setDescription(description);;
Can we remove this commented out line of code?

2022-05-30 17:58 UTC, pconrad commented
LGTM.  It would be good to add some validation, i.e. 
* the enrollCd should be numeric and no more than five digits
* the psId should be the id of an existing personal schedule in the personal schedule table
* the quarter should be a legal quarter in yyyyq format, i.e. yyyy should be between 1900 and 2099, and q should be 1, 2, 3 or 4

And if any of those are not true, the controller throws an IllegalArgumentException.

But that can be a separate issue that someone can work on.  (I'll add it as an issue.)

2022-05-30 19:51 UTC, pconrad approved these changes

2022-05-30 19:52 UTC, merged