s22-6pm-2 Yufei Backend API get courses by psId
ucsb-cs156-s22/s22-6pm-courses pull request #31
Opened 2022-05-27 07:43 UTC by Sean-syf

Given a personal schedule ID, return all courses of the personal schedule ID.
<img width="1187" alt="Screen Shot 2022-05-28 at 9 41 46 PM" src="https://user-images.githubusercontent.com/73827652/170852557-f5139fc5-380e-4700-b25c-95fec8e61f93.png">
Coses #30

2022-05-30 02:05 UTC, austinmacmath submitted a review, later dismissed
LGTM

2022-05-31 07:19 UTC, andrewhlu requested changes

2022-05-31 07:19 UTC, andrewhlu commented on src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
> +        PersonalCourses p3 = PersonalCourses.builder().psId(2).enrollCd("654321").quarter("20222").id(2L).build();
This test is testing that, if the endpoint is called with `psID = 1`, that all `psID = 1` is returned. This personal course has `psID = 2`, so it probably shouldn't be returned...

2022-05-31 07:20 UTC, andrewhlu reviewed
Tested functionality on Heroku and it looks good, once we get the small issue with the unit test fixed, this should be good to go!

2022-06-02 21:28 UTC, merged