s22-6pm-2 Yufei Modify Add Course API
ucsb-cs156-s22/s22-6pm-courses pull request #35
Opened 2022-05-30 10:54 UTC by Sean-syf

Create a stub method
The stub method returns true if enrollcode length is 6 and quarter length is 5. Otherwise, return false.
It will be replaced by a course search method.

If the stub method returns false then add course API returns an error with message "course not found"

<img width="1283" alt="Screen Shot 2022-05-30 at 3 50 01 AM" src="https://user-images.githubusercontent.com/73827652/170977165-9455fe42-7caa-4d0c-b93a-c68e8636c20b.png">

2022-05-31 03:53 UTC, austinmacmath submitted a review, later dismissed
lgtm

2022-05-31 21:26 UTC, austinmacmath approved these changes
LGTM

2022-06-04 17:48 UTC, mikeycurtis approved these changes
LGTM

2022-06-04 18:36 UTC, pconrad approved these changes
LGTM... I like that we are doing a simple validation first, and then replacing it later with a better validation.  This is a nice incremental approach!

I'll test it on QA before merging.

2022-06-05 03:48 UTC, pconrad requested changes

2022-06-05 03:48 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
> +        }
This is good! 

But you should also validate the psId.

Do a personalScheduleRepository.find(psId) and if it doesn't find it, you should ALSO reject that as an invalid request.  You could throw an EntityNotFoundException.

2022-06-05 10:01 UTC, closed without merging