s22-6pm-2 Nirmit Method for Section information given enroll code and quarter
ucsb-cs156-s22/s22-6pm-courses pull request #57
Opened 2022-05-31 22:36 UTC by nirmitashar

I created the endpoint for section information given enroll code and quarter and its associated tests. I then used pitest and jacoco for test and mutation coverage.
<img width="1149" alt="Screen Shot 2022-05-31 at 3 35 00 PM" src="https://user-images.githubusercontent.com/13338417/171295065-f1f7e060-71e5-452c-a8b5-fa56131e92f0.png">
<img width="1149" alt="Screen Shot 2022-05-31 at 3 35 30 PM" src="https://user-images.githubusercontent.com/13338417/171295120-3a5a1c21-d469-4788-82c7-14f058fd4d6b.png">

2022-05-31 23:46 UTC, Sean-syf approved these changes

2022-05-31 23:49 UTC, Sean-syf commented
LGTM

2022-06-01 10:16 UTC, Sean-syf requested changes
endpoint link should be "https://api.ucsb.edu/academics/curriculums/v1/classsection/quarter/enrollCd"
the link in the code might not work

2022-06-01 20:13 UTC, andrewpengucsb approved these changes
LGTM!

2022-06-01 20:13 UTC, merged